version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: progresstracker
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: progresstracker
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/_data
  progresstracker-backend:
    build: ./
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://progresstracker:backend@postgres/progresstracker
    ports:
      - 8443:8443
    depends_on:
      - postgres
